final-project-onlineshop/teknoza

backend/requests.http, backend/test.rest
=> basic test added as request.http and test.rest..

backend/index.js
=> bkr-update-data-model : data model is updated..

backend/config.js, backend/package-lock.json, frontend/package-lock.json, frontend/package.json, frontend/src/App.tsx, frontend/src/pages/dashboardPage/DashboardPage.tsx, frontend/src/pages/homePage/HomePage.tsx
=> Omer : create dashboard screen

frontend/src/App.tsx, frontend/src/components/header/Header.tsx, frontend/src/pages/ordersPage/OrdersPage.tsx
=> Omer create order list screen

frontend/src/App.tsx, frontend/src/pages/productEditPage/ProductEditPage.tsx
=> omer : product edit page created

frontend/src/App.tsx, frontend/src/pages/usersPage/UsersPage.tsx
=> omer : users page created

frontend/src/App.tsx, frontend/src/pages/productsPage/ProductsPage.tsx, frontend/src/pages/productsPage/productsPage.scss
=> omer : products screen created

backend/routes/productRoutes.js, backend/test.rest
api/product/:id and slug/:slug paths is ready to use.. no bug anymore.. closes #107
=> bkr-fix-connection-withid : api/product/:id and slug/:slug paths fixed.. closes #107

backend/routes/productRoutes.js, backend/test.rest
closes #110. with online coding we fixed together this bug..
=> bkr-fix-bug-inidroute : fixed bug in id routes with try and catch..

backend/routes/seedRoutes.js
=> bkr-create-seed-router : created seedRouter..

backend/data.js
=> bkr-create-datajs : updated data.js with our basic database..

backend/config.js, backend/index.js, backend/models/userModel.js, backend/test.rest
auths is working.. login or signin is ready..closes #124
=> bkr-test-auths : auths tested.. 

backend/utils.js
=> bkr-create-gmail: gmail account created and added to .env..

.gitignore, .vscode/settings.json, frontend/src/components/header/Header.tsx, frontend/src/pages/cartPage/CartPage.tsx, frontend/src/pages/dashboardPage/DashboardPage.tsx, frontend/src/pages/homePage/HomePage.tsx, frontend/src/pages/loginPage/LoginPage.tsx, frontend/src/pages/orderHistoryPage/OrderHistoryPage.tsx, frontend/src/pages/ordersPage/OrdersPage.tsx, frontend/src/pages/paymentPage/PaymentPage.tsx, frontend/src/pages/placeOrderPage/PlaceOrderPage.tsx, frontend/src/pages/productEditPage/ProductEditPage.tsx, frontend/src/pages/productPage/ProductPage.tsx, frontend/src/pages/productsPage/ProductsPage.tsx, frontend/src/pages/registerPage/RegisterPage.tsx, frontend/src/pages/shippingPage/ShippingPage.tsx, frontend/src/pages/usersPage/UsersPage.tsx
=> Omer update browser title with inhalt

backend/index.js, backend/routes/orderRoutes.js, backend/test.rest
=> bkr-create-order-router : order router created..

frontend/src/App.tsx, frontend/src/pages/orderDetailsPage/OrderDetailsPage.tsx
=> omer : order details page created

backend/routes/userRoutes.js, backend/test.rest, frontend/package-lock.json
all testings is working, except signup route.. closes #145.
=> bkr-add-new-testing : new route testing added to test.rest..

backend/routes/productRoutes.js, backend/routes/userRoutes.js, backend/test.rest
=> bkr-fix-ug-in-post-product : bug fixed and tested..

backend/routes/productRoutes.js, backend/test.rest
=> bkr-fix-search-product-bug :  search path is ready..

backend/test.rest
if you did not update your main branch. use git stash to save your changes to stash. switch main and git pull.. call git stash apply on terminal.
=> bkr-test-githash : testing git stash

frontend/package-lock.json, frontend/src/pages/registerPage/RegisterPage.tsx
=> sevde: connected registerPage with backend, closes #154

backend/index.js, backend/routes/productRoutes.js
=> bkr-check-product-routes : updated.. und bug fixed.. have to be tested..

frontend/src/components/product/Product.tsx, frontend/src/components/rating/Rating.tsx, frontend/src/pages/productPage/ProductPage.tsx
=> Omer fix be connections for new update

frontend/src/components/orderSummary/OrderSummary.tsx, frontend/src/pages/orderDetailsPage/OrderDetailsPage.tsx, frontend/src/pages/placeOrderPage/PlaceOrderPage.tsx
=> Omer create order summary component

frontend/package-lock.json, frontend/package.json, frontend/src/pages/loginPage/LoginPage.tsx, frontend/src/pages/loginPage/loginPage.scss, frontend/src/pages/registerPage/RegisterPage.tsx, frontend/src/pages/registerPage/registerPage.scss
=> sevde: added useFormik for validations before backend, closed #121

frontend/src/App.tsx, frontend/src/Store.tsx, frontend/src/components/adminRoute/AdminRoute.tsx, frontend/src/components/header/Header.tsx, frontend/src/components/protectedRoute/ProtectedRoute.tsx, frontend/src/pages/loginPage/LoginPage.tsx, frontend/src/pages/registerPage/RegisterPage.tsx
=> Omer create private routing

frontend/src/pages/productPage/ProductPage.tsx, frontend/src/pages/productPage/productPage.scss
Added photo-albums instead of carousel, closed #166
=> sevde: added photo-album in product datails page

backend/routes/productRoutes.js, backend/test.rest
solved the search problems.. closes #172.
=> bkr-fix-sarch-bug : fixed bug.. can be tested with test.rest..

frontend/src/pages/loginPage/LoginPage.tsx, frontend/src/pages/registerPage/RegisterPage.tsx
Submit-functions converted to asynchronous
=> sevde: bug fixed in Login Page and Register Page, closes #175

backend/models/productModel.js, backend/routes/productRoutes.js, backend/routes/userRoutes.js, backend/test.rest
at first token bug in signin must be fixed.. after that can be tested.. closes #177.
=> bkr-fix-product-post-put : fixed. but can not be tested.

backend/requests.http
updated hetzner testing.. our database must be updated.. because of security measures.. i will change our users.. closes #179
=> bkr-add-hetzner-testing : updated test for hetzner backend route..

backend/index.js
=> bkr-update-database : database updated..

backend/.gitignore, backend/index.js
=> bkr-add-test-gitignore : added all test files to gitignore..

frontend/src/pages/cartPage/CartPage.tsx
=> omer : ptc button fixed

frontend/src/components/header/Header.tsx
=> omer : fixed badge count in cart

frontend/src/Store.tsx, frontend/src/pages/shippingPage/ShippingPage.tsx
=> Omer update shipping page as dynamically

frontend/src/Store.tsx, frontend/src/components/addToCartButton/AddToCartButton.tsx, frontend/src/components/addToCartButton/addToCartButton.scss, frontend/src/components/product/Product.tsx, frontend/src/components/product/product.scss, frontend/src/components/productInCart/ProductInCart.tsx, frontend/src/pages/productPage/ProductPage.tsx, frontend/src/pages/searchPage/SearchPage.tsx
=> omer : add to cart button component created

backend/routes/productRoutes.js, backend/test.rest
=> bkr-fix-bug-in-product-search : bug fixed. but must be checked with frontend..

backend/routes/productRoutes.js
=> bkr-fx-bug-in-reviews : bug fixed..

backend/.gitignore, backend/test.rest
=> bkr-add-test-rest : added test.rest without token and users..

backend/utils.js
=> bkr-fix-bug-bearer : fixed

frontend/src/App.tsx, frontend/src/components/header/Header.tsx, frontend/src/pages/profilePage/ProfilePage.tsx
=> fix account link in user menu, #closes 200

backend/routes/userRoutes.js
=> bkr-fix-bug-in-profile : /profile user update fixed.. 

backend/config.js
=> bkr-fix-paypal-client : bug fixed..

frontend/src/pages/orderDetailsPage/OrderDetailsPage.tsx, frontend/src/pages/orderHistoryPage/OrderHistoryPage.tsx, frontend/src/pages/ordersPage/OrdersPage.tsx, frontend/src/pages/placeOrderPage/PlaceOrderPage.tsx, frontend/src/utils.js
=> Omer update orders page for admins dynamically

backend/routes/productRoutes.js, frontend/src/pages/orderDetailsPage/OrderDetailsPage.tsx, frontend/src/pages/productsPage/ProductsPage.tsx
=> omer : admin products page updated

frontend/src/pages/placeOrderPage/PlaceOrderPage.tsx, frontend/src/pages/productEditPage/ProductEditPage.tsx, frontend/src/pages/profilePage/ProfilePage.tsx
=> Omer update admin edit product page dynamically

frontend/src/App.tsx, frontend/src/pages/placeOrderPage/PlaceOrderPage.tsx, frontend/src/pages/productEditPage/ProductEditPage.tsx, frontend/src/pages/profilePage/ProfilePage.tsx, frontend/src/pages/userEditPage/UserEditPage.tsx, frontend/src/pages/usersPage/UsersPage.tsx
=> Omer update admin users list dynamically

backend/routes/orderRoutes.js, backend/routes/productRoutes.js, backend/test.rest, backend/utils.js
=> bkr-fix-bug-in-nodemailer : bug fixed..
